In [1]:
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
import json
#from scipy import stats
#import scipy.interpolate as interp
from pprint import pprint
%matplotlib inline
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 14

In [2]:
import FEMmodule as FEM

# Toy FEM - python version

This code is the Python replica of the matlab code used in *LAB01* of the course **Nonlinear Analysis of Aerospace Structures** held by Marco Morandini, Riccardo Vescovini at *Politecnico di Milano*

## Build matrices

- *nodes* matrix: containing nodes coordinates
- *elements* matrix: connectivity matrix associating nodes to elements
- *constrained elements* vector: list of constrained (fixed) nodes

Parameters are **nx** and **ny**: number of elements in *x* and *y* directions.

Default plate size is l=10, w=2. It can be changes passing additional parameters to **Nodes**

In [3]:
nx = 2
ny = 2
l = 10.
w = 2.

In [4]:
nodes, elements, constr_nodes = FEM.Nodes(nx,ny)
#nodes, elements, constr_nodes = FEM.Nodes(nx,ny, l, w)

Create a Gaussian integrator for **2D** 2$\times$2 matrix

In [5]:
GI = FEM.GaussIntegr2D2x2()

Create a *plane stress* **Elastic Tensor** with parameters **E** and **$\nu$**

In [6]:
E = FEM.PlaneStressElasticTensor(1.e4, 0.3)

Create a set of *bilinear weights*, used to interppolate a **2D** function on a $(x,y)$ grid

In [7]:
W = FEM.BilinearWeights()

Build vectors of *constrained* and *free* **DOFs**

In [8]:
constr_dofs = np.append(constr_nodes, constr_nodes + nodes.shape[0])
free_dofs = np.array([i for i in range(0,2*nodes.shape[0]) if i not in constr_dofs])

Build matrices

In [9]:
ne = nodes.shape[0]*nodes.shape[1]
GlobalStiff = np.zeros((ne,ne))
GlobalRes = np.zeros(ne)
GlobalDispl = np.zeros_like(GlobalRes)

**Force** vector: $[F_x , F_y]$

In [10]:
force = np.array([0. ,1.])

Compute:

In [11]:
for e in range(elements.shape[0]):
    Stiff = GI.Integrate(lambda x : FEM.ElementLocalStiffness(nodes[elements[e,:].astype(int),:], E, W, x) )


0
[[ 0.  0.]
 [ 5.  0.]
 [ 5.  1.]
 [ 0.  1.]]
<FEMmodule.PlaneStressElasticTensor instance at 0x7f3b80886d40>
<FEMmodule.BilinearWeights instance at 0x7f3b808861b8>
2.79953837889e-12
1
[[  5.   0.]
 [ 10.   0.]
 [ 10.   1.]
 [  5.   1.]]
<FEMmodule.PlaneStressElasticTensor instance at 0x7f3b80886d40>
<FEMmodule.BilinearWeights instance at 0x7f3b808861b8>
4.83169060317e-13
2
[[ 0.  1.]
 [ 5.  1.]
 [ 5.  2.]
 [ 0.  2.]]
<FEMmodule.PlaneStressElasticTensor instance at 0x7f3b80886d40>
<FEMmodule.BilinearWeights instance at 0x7f3b808861b8>
-4.56168436358e-12
3
[[  5.   1.]
 [ 10.   1.]
 [ 10.   2.]
 [  5.   2.]]
<FEMmodule.PlaneStressElasticTensor instance at 0x7f3b80886d40>
<FEMmodule.BilinearWeights instance at 0x7f3b808861b8>
-7.30437932361e-12
